### ISSUE TITLE
Can't complete request

### ISSUE THREAD

**Issue by SemenMartynov** [alyobabi/xml2json#3]
```
sam@spb$ curl -d "world" -X POST http://0.0.0.0:80/xml
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>
```

**Comment by SemenMartynov** [comment]
```
sam@spb$ curl -d @example.xml -X POST http://0.0.0.0:80/xml
Warning: Couldn't read data from file "example.xml", this makes an empty POST.
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>
```

```
[2018-12-18 05:16:19,086] ERROR in app: Exception on /xml [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "appf.py", line 30, in xml2json
    req_payload = ET.fromstring(request.get_data(as_text = True))
  File "/usr/local/lib/python3.7/xml/etree/ElementTree.py", line 1316, in XML
    return parser.close()
  File "<string>", line None
xml.etree.ElementTree.ParseError: no element found: line 1, column 0
172.17.0.1 - - [18/Dec/2018 05:16:19] "POST /xml HTTP/1.1" 500 -
```

```
<?xml version="1.0" encoding="UTF-8"?>
<note>
  <to>Tove</to>
  <from>Jani</from>
  <heading>Reminder</heading>
  <body>Don't forget me this weekend!</body>
</note>
```

**Comment by alyobabi** [comment]
> ```
> sam@spb$ curl -d "world" -X POST http://0.0.0.0:80/xml
> <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
> <title>500 Internal Server Error</title>
> <h1>Internal Server Error</h1>
> <p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>
> ```

Fixed syntax error in Markdown. `curl -d "<hello>world</hello>" -X POST http://0.0.0.0:80/xml`
> ```
>  sam@spb$ curl -d @example.xml -X POST http://0.0.0.0:80/xml
> Warning: Couldn't read data from file "example.xml", this makes an empty POST.
> <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
> <title>500 Internal Server Error</title>
> <h1>Internal Server Error</h1>
> <p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>
> ```
And added example.html. 

Request: `curl -d @example.xml -X POST http://0.0.0.0:80/xml`

Answer: `{"abdera":{"note":{"children":[{"to":"Tove"},{"from":"Jani"},{"heading":"Reminder"},{"body":"Don't forget me this weekend!"}]}},"badgerfish":{"note":{"body":{"$":"Don't forget me this weekend!"},"from":{"$":"Jani"},"heading":{"$":"Reminder"},"to":{"$":"Tove"}}},"cobra":{"note":{"attributes":{},"children":[{"to":"Tove"},{"body":"Don't forget me this weekend!","from":"Jani","heading":"Reminder"}]}},"gdata":{"note":{"body":{"$t":"Don't forget me this weekend!"},"from":{"$t":"Jani"},"heading":{"$t":"Reminder"},"to":{"$t":"Tove"}}},"parker":{"body":"Don't forget me this weekend!","from":"Jani","heading":"Reminder","to":"Tove"},"yahoo":{"note":{"body":"Don't forget me this weekend!","from":"Jani","heading":"Reminder","to":"Tove"}}}`
